# @package _global_
model_name: dimsum
model:
  _target_: models.DiMSUMRestoration
  in_channels: 3
  out_channels: 3
  patch_size: 8
  patch_hidden_size: 96
  hidden_size: 384
  depth: 16
  num_heads: 8
  global_num_heads: 16
  state_size: 16
  convolution_size: 4
  expansion: 2
  mlp_ratio: 4.0
  global_attention_interval: 4
