# @package _global_
model_name: dimsum_rf
model:
  _target_: models.DiMSUMRectifiedFlow
  sample_steps: 20
  timestep_scale: 1000.0
  out_channels: 3
  patch_size: 8
  patch_hidden_size: 96
  hidden_size: 384
  depth: 16
  num_heads: 8
  global_num_heads: 16
  state_size: 16
  convolution_size: 4
  expansion: 2
  mlp_ratio: 4.0
  global_attention_interval: 4

model_scheduler:
  _target_: schedulers.warmup_cosine
  total_epochs: ${train.epochs}
  warmup_epochs: 5
  min_lr_ratio: 0.05
