dataset:
  df2k:
    train_dir: /mnt/sda3/Documents/Datasets/DF2K/DF2K_train_HR
    val_dir: /mnt/sda3/Documents/Datasets/DF2K/DF2K_valid_HR
  bsds500:
    val_dir: /mnt/sda3/Documents/Datasets/BSDS500/images/test
  urban100:
    val_dir: /mnt/sda3/Documents/Datasets/Urban100
    glob: "**/*_HR.png"

model: fbcnn

train:
  start_checkpoint: fbcnn.pt
  epochs: 50
  lr: 1e-5
  batch_size: 32
  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [30]
    gamma: 0.5

eval:
  dataset: bsds500
  checkpoint: ""
