defaults:
  - base
  - override model: dimsum_rf
  - _self_

train:
  start_checkpoint: dimsum_rf_200e.pt
  resume_optimizer: false
  resume_scheduler: false
  epochs: 500
  lr: 1.5e-5
  batch_size: 32
  sample_every: 10
  val_seed: 0
  compile:
    enabled: true

model_scheduler:
  _target_: schedulers.warmup_cosine
  total_epochs: 300
  warmup_epochs: 5
  min_lr_ratio: 0.1

eval:
  dataset: df2k
  checkpoint: dimsum_rf_200e.pt
