defaults:
  - base
  - _self_

train:
  start_checkpoint: fbcnn.pt
  epochs: 50
  lr: 1e-5
  batch_size: 32
  scheduler:
    _target_: torch.optim.lr_scheduler.MultiStepLR
    milestones: [30]
    gamma: 0.5

eval:
  dataset: bsds500
