defaults:
  - base
  - _self_

dataset:
  lsdir_00:
    - /mnt/projects/models/01-datasets/LSDIR/shard-00/0001000
    - /mnt/projects/models/01-datasets/LSDIR/shard-00/0002000
    - /mnt/projects/models/01-datasets/LSDIR/shard-00/0003000
    - /mnt/projects/models/01-datasets/LSDIR/shard-00/0004000
    - /mnt/projects/models/01-datasets/LSDIR/shard-00/0005000
  lsdir_01:
    - /mnt/projects/models/01-datasets/LSDIR/shard-01/0006000
    - /mnt/projects/models/01-datasets/LSDIR/shard-01/0007000
    - /mnt/projects/models/01-datasets/LSDIR/shard-01/0008000
    - /mnt/projects/models/01-datasets/LSDIR/shard-01/0009000
    - /mnt/projects/models/01-datasets/LSDIR/shard-01/0010000

train:
  datasets: [df2k_train, lsdir_00, lsdir_01]
  start_checkpoint: rela_dit_meanflow.pt
  epochs: 300
  crop_size: 128
  val_crop_size: 128
  batch_size: 32
  lr: 3e-5
  exploration: 3
  sample_every: 10
  val_seed: 0
  compile:
    enabled: true

lr_scheduler:
  _target_: schedulers.warmup_cosine
  total_epochs: ${train.epochs}
  warmup_epochs: 5
  min_lr_ratio: 0.05

eval:
  datasets: [df2k_val]
  checkpoint: ""
